apiVersion: skaffold/v1beta1
kind: Config
build:
  artifacts:
    - image: gcr.io/searce-sandbox/abc
      context: .
      #- image: gcr.io/searce-sandbox/xyz
      #context: .
  kaniko:
    buildContext:
    # localDir: {}
     gcsBucket: mukesh-test-bucket
    pullSecret: /workspace/kaniko-key.json
    namespace: build-helloworld
    cache: {}

deploy:
   kustomize: {}
